### ISSUE TITLE
Behavior of property "valid" of object "processDataIOL" (Table 61) unclear

### ISSUE THREAD

**Issue by mrentsch65** [iolinkcommunity/JSON_for_IO-Link#107]
Reported in [CR 129](https://www.io-link-projects.com/) by Steffen.Riedel@murrelektronik.de:

The object "processDataIOL" is used in the payload of
- 5.7.5 GET /processdata/value
- 5.7.6 GET /processdata/getdata/value
- 5.7.7 GET /processdata/setdata/value
- 5.7.8 POST /processdata/value
 
The property "valid" is part of this object. The description indicates a special behavior for "output data". The behavior for "input data" is not specified.
 
My implications:
- For "input data", the state of the Property "valid" shall correspond to the Port Qualifier (PQ)
- For "output data", the Property "valid" is always true either on setting via 5.7.8 or reading back "setdata" via 5.7.5 or 5.7.7. For 5.7.8 it is not clear what happens if the Property is false.
 
Note: Found in Version JSON_Integration_10222_V100_Mar20.pdf

**Comment by roesekoSICKAG** [comment]
I agree that's something we should review. Especially, it should always be `true ` in case of setting the output data according the specification (JSON_Integration_10222_V100_Mar20.pdf). 
![image](https://github.com/iolinkcommunity/JSON_for_IO-Link/assets/95340986/86cda219-8f0e-461b-9b64-043e9f805b46)

**Comment by roesekoSICKAG** [comment]
2023/10/16 Update after discussion in workgroup meeting:
Remark that it is actually necessary and should be bound to mastercommand “ProcessDataOutputOperate” / OE.
