### ISSUE TITLE
Add 401 http status code for all endpoints

### ISSUE THREAD

**Issue by julian-st** [iolinkcommunity/JSON_for_IO-Link#128]
At the moment there are a few calls in the version-1-x spec that contain this response
 "401":
          $ref: "#/components/responses/HTTP_401"

This response should be added to more or all endpoints.

This does not mean that a authentication handling is obligatory but it enables the vendor to use it if possible.

**Comment by roesekoSICKAG** [comment]
Issue already resolved as discussed on 29th of April.
