### ISSUE TITLE
Monitoring current and or voltage at port

### ISSUE THREAD

**Issue by fm-sick** [iolinkcommunity/JSON_for_IO-Link#129]
this for CR 103 on project server:

copy from the project server
Add or adjust requests for reading current and voltage values of the gateway itself and its ports.

Meeting 15.2.2021 accepted as optional endpoints Proposal: Get /status for the gateway / master / ports optional for all. Discussion: shall this also described in master capabilities like “extended diagnostic”..?

**Comment by roesekoSICKAG** [comment]
Created /monitor endpoint for gateway and ports to read the voltage and current. 
The following properties shall be returned: 

Ports: 
- Voltage (cqVoltage, iqVoltage, primaryVoltage, secondaryVoltage) 
- Current (cqCurrent, iqCurrent, primaryCurrent, secondaryCurrent) 
- Wireless quality (lqiMaster, rssiMaster, lqiDevice, rssiDevice) 

Gateway:
- Voltage (primaryVoltage, secondaryVoltage) 
- Current (primaryCurrent, secondaryCurrent)
