### ISSUE TITLE
Clarify GET /device/{deviceAlias}/processdata/value response when no PD is available in OPERATE

### ISSUE THREAD

**Issue by alexkrizsan** [iolinkcommunity/JSON_for_IO-Link#137]
Let's assume the following configuration:
- CQ: IO-Link Autostart
- IQ: Not supported
- V1.1 Device attached to the Port with without PD

It is possible to have no PD (in and out) in OPERATE, see V1.1.3 Interface Spec. 19June, Table A.10. In the endpoint's response "getData" and "setData" objects are both empty. The "cqValue" and "iqValue" properties should not be present due to portconfig. There is no PD, thus "iolink" property is skipped. If "getData" and "setData" are empty objects they can also be skipped. They are optional.

In this case, only an empty object should be returned. That is the intended behavior?

**Comment by roesekoSICKAG** [comment]
Discussion in WG meeting (23/09/2023):
In that case the response should look like:
GET "/devices/{deviceAlias}/processdata/value"
```
{
  "getData": {
  },
  "setData": {
  }
}
```
GET "/devices/{deviceAlias}/processdata/getdata/value"
```
{
}
```
GET "/devices/{deviceAlias}/processdata/setdata/value":
```
{
}
```
The description of these endpoints need to be adjusted as well.
```
The cqValue is present in the 'getData' object if the CQ (pin4) is configured as digital input. The cqValue is present in the 'setData' object if the CQ (pin4) is configured as digital output. The iolink is present in the 'getData' if the port is configured to IO-Link mode and the device provides input process data. The iolink is present in the 'setData' if the port is configured to IO-Link mode and the device provides output process data. The iqValue is present in the 'getData' object if the IQ (pin2) is configured as digital input. The iqValue is present in the 'setData' object if the IQ (pin4) is configured as digital output.
```
