### ISSUE TITLE
Create separate endpoints for the wireless extension.

### ISSUE THREAD

**Issue by alexkrizsan** [iolinkcommunity/JSON_for_IO-Link#140]
In the GET /masters/{masterNumber}/ports/{portNumber}/status and GET + POST /masters/{masterNumber}/ports/{portNumber}/configuration endpoints the wireless extension related properties are added to the schemas. It's not clear what is the expected structure for wireless or non-wireless cases. 

Consider creating a new endpoint or define the wireless and non-wireless structures separately and use "oneOf" to combine them.

**Comment by roesekoSICKAG** [comment]
Discussion in WG meeting (23/09/2024):
You have an point here, but we could not find a better way of describing this in order to maintain the useability and keep wired and wireless ports as similar as possible.
