### ISSUE TITLE
How is the yaml intended to be used?

### ISSUE THREAD

**Issue by spflieger** [iolinkcommunity/JSON_for_IO-Link#36]
I wonder how this API description is intended to be used. The description in the YAML file and the JSON Integration for IO-Link specification suggest that this YAML file is intended as a template. 
So every IO-Link gateway vendor creates a API description for his device?
Or shall this YAML file usable for every IO-Link gateway that implements the JSON Integration for IO-Link specification?

**Comment by mrentsch65** [comment]
Hi Sebastian :-)

this matches:
> ... Or shall this YAML file usable for every IO-Link gateway that implements the JSON Integration for IO-Link specification?

Best Regards,
            Markus
