### ISSUE TITLE
Updating in YAML schema the adressing parameters to strings

### ISSUE THREAD

**Issue by mrentsch65** [iolinkcommunity/JSON_for_IO-Link#60]
From [CR ID 128](https://www.io-link-projects.com/view_crs_page.php?project_id=207) "URL address parameters should be strings, not integers":

The URL address parameters like **{topicId}**, {**masterNumber}**, **{portNumber}** are defined as integer numbers. This limits future usage with more sophisticated addressing concepts like already defined for **{deviceAlias}** and would for example  allow for the {portNumber} the use of the descriptive port name for adressing purposes.

Although it would be nice to consequently also change the names from {masterNumber} to {masterId} and {portnumber} to {portId}, this would in fact create a comaptibility issue, because these names are already used in the the JSON data objects.

I therefore suggest only to change the type of these parameters to "string" to allow also descriptive identifiers, which does not create any backward compatibility issues.

**Comment by vervoortb** [comment]
alternative idea: introduce a "masterAlias" in addition to the masterNumber similiar to the deviceAlias relation to the portNumber

**Comment by fm-sick** [comment]
There is already for master a location tag defined which is intended to give the master a meaningful name   
[
  {
    "masterNumber": 1,
    "serialNumber": "A12345678B",
    "locationTag": "slot 5"
  },
  {
    "masterNumber": 2,
    "serialNumber": "123A45B783",
    "locationTag": "slot 6"
  }
]

**Comment by mrentsch65** [comment]
Defining an additional "masterAlias" does not solve the initial purpose to have also string adressing in the endpoint URL. 
The only difference will be that `"masterNumber": "1"` is returned in the JSON response instead of `"masterNumber:" 1`, which should not lead to a backward compatibility issue.

**Comment by roeseko** [comment]
I understand and like this change request, but this type alteration would definitely be a breaking change. Therefore I doubt the reasoning and suggest to leave it for now as it is.

**Comment by mrentsch65** [comment]
> 
@roeseko: I feel that subjects have been mixed here and was unfortunatley not present yesterday, when that "closing"-discussion took place. 
This "masterAlias"-idea was never part of the original issue, it was later introduced in the discussion by someone. 
But the original topic (format change from integer to string) is something different and why should this be a breaking change ? It was clearly argumented that it does not create compatibility problems.
