### ISSUE TITLE
Allow download of open api description from device

### ISSUE THREAD

**Issue by roeseko** [iolinkcommunity/JSON_for_IO-Link#66]
It would be really nice to have a description of the api downloadable from the gateway device. Either in yaml or json format. As a path I suggest: http://{ipAddress}/iolink/v1/openapi

Responses:accepted in principle See also CR 108 
A directory is usefull for reading the implemented functionality also for testingToday in specification there are mandatory and optional resources (mandatory are guaranteed) clients can relay on this. Also the system behavior is defined. Format of the response shall be YAML or JSON by query parameter ? This should be mandatory a) as a real specific instance file or b) as a vendor specific link c) community hosted standard YAML file link. => To do for IO-Link.com providing a link (like for the checker)

_(www.io-link-projects.com CR 102)_

**Comment by mrentsch65** [comment]
I propose to make this endpoint generic to be able to allow access to multiple YAML-files, if multiple REST-APIs are supported from a target. Path could be then http://{ipAddress}/openapi

**Comment by roeseko** [comment]
I agree this would make total sense to have a general, common entry point. But I am not sure what would be the best way to realize this. 
What would be your expectation when doing a GET request on this path?
- one yaml file containing all supported REST-APIs
- or an array of links to each, separate yaml file of the REST-API

**Comment by mrentsch65** [comment]
I would recommend an endpoint "GET /apidocs" outside the iolink-basepath. The response returns a list of Download-URLs of the specification files. These links can either point to the embedded device or to a web location. One of these links will point to the yaml.file of the JSON-IO-Link-API.

**Comment by roeseko** [comment]
Alright, I understand and agree. In my opinion we are not in the position to specify any endpoints outside of the /iolink/ domain, but maybe we can include this one as a suggestion to the specification document.

Regarding the original question, I will add the specific path http://{ipAddress}/iolink/v1/openapi with the three examples:
- concrete yaml file
- vendors link
- iolink community link 

Any remarks?

**Comment by roeseko** [comment]
Hi @mrentsch65 
My plan is to have it done for the next working group meeting 13.01.23.
