### ISSUE TITLE
Review MQTT chapter and convert into asyncapi document

### ISSUE THREAD

**Issue by roesekoSICKAG** [iolinkcommunity/JSON_for_IO-Link#71]
There are certain ambiguities in the MQTT chapter of the specification:

1. topicName can be configured, but there are no rules mentioned. Probably the same as for the device alias ("A device name must only contain alphanumeric characters and underscores.") 
2. **Idea:** Maybe it makes sense to deliver directly the corressponding regex expression (same applies to other parts of the specification like "Naming based on IODD")
3. client name is missing in the configuration (with suggested default value) not sure but I think it has to be unique
4. head topic is missing in the configuration (with suggested default value)
5. master/device identification via MQTT only on connect or does it make sense to do it cyclically
6. publish mechanism of parameters 
7. publish/subscribe channel to read/write parameters

**Comment by mrentsch65** [comment]
1. Yes, rules should be formulated
2. Yes, good idea
3. Yes, should be added
4. Yes, should be added
5. How is this usally handled in MQTT implementations?
6. Do not quite understand
7. Do not quite understand
@roeseko : Do you have actual improvement proposals you would like to commit?

**Comment by mrentsch65** [comment]
In my original  submission of [MQTT_for_IO-Link.yaml](https://raw.githubusercontent.com/iolinkcommunity/JSON_for_IO-Link/version-1-x/MQTT_for_IO-Link.yaml#operation-subscribe-{originatorId}/{deviceId}/processData), there is the concept of the "originatorId", which shall be the unique identifier of the originating MQTT publish messages (thus in our case identifying the IO-Link-Gateway). It shall correspond to the client id inside the MQTT message. It can be the ProductURI, DNS name, IP address or MAC address of the gateway device hosting the MQTT publisher. By default the Hostname shall be used.

**Comment by roeseko** [comment]
Discussion in WG meeting (21/03/2023):
OpenAPI changes:
- baseTopic is the equivalent to originatorId
- add “baseTopic” property to "mqttConfigurationGetPost" -> optional, (default shall be MAC address) 
- open question if colons are allowed -> TODO @roeseko: find out for the next time!

- introduce "last will" default config
- topic -> “connection”
- message -> “offline”

AsyncAPI changes:
- introduce baseTopic
- keep document as small as possible without any identification extensions

**Comment by mrentsch65** [comment]
Found with "sparkplug" an interesting approach that we could adapt: 
https://sparkplug.eclipse.org/
https://www.informatik-aktuell.de/betrieb/netzwerke/sparkplug-eine-auf-mqtt-basierende-spezifikation-fuer-das-iiot.html
![image](https://github.com/iolinkcommunity/JSON_for_IO-Link/assets/50681355/2eb4a72a-a081-468f-89ca-15bf048ad211)

**Comment by roesekoSICKAG** [comment]
> Discussion in WG meeting (21/03/2023): OpenAPI changes:
> * open question if colons are allowed -> TODO @roeseko: find out for the next time!

From MQTT spec https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901247
"Topic Names and Topic Filters are UTF-8 Encoded Strings; they MUST NOT encode to more than 65,535 bytes"
The only restriction is: 
"Topic Names and Topic Filters MUST NOT include the null character (Unicode U+0000) [[Unicode]](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#Unicode) [MQTT-4.7.3-2]"

**Comment by roesekoSICKAG** [comment]
In general the request response mechanism is independent of the used mqtt version but V5 has some more features to improve the communication like:
•	Response Topic for dynamic response channels
•	Correlation Data is used to map request to response -> a mechanism for this for 3.1.1 could be to introduce something like a client transaction id as part of the topic

**Comment by roesekoSICKAG** [comment]
Done
