### ISSUE TITLE
Review and discuss changes between branch version-1-x and the official release 1.0.0 

### ISSUE THREAD

**Issue by roeseko** [iolinkcommunity/JSON_for_IO-Link#72]

**Comment by mrentsch65** [comment]
@roeseko : Can we name the changes to discuss here? Which ones do you have in mind?

**Comment by roeseko** [comment]
The general idea behind this issue is to have an overview, like release notes, to understand and integrate the changes of this branch.

Introduction "operationId" and "description"

There are some endpoints which are new and have not been discussed as far as I know. These are:
- /login
- /logout
- /specs
- /gateways
- /masters/{masterNumber}/configuration -> part of the wireless discussion 
- /masters/{masterNumber}/tracks -> part of the wireless discussion 

statusInfo in /masters/{masterNumber}/ports and /masters/{masterNumber}/ports/{portNumber}/status

Create response error schema as reference (pretty straight forward) 

Example values in proper yaml format. Added unit example.

New properties for in gatewayIdentificationGet
- orderCode
- vendorUrl
- manualUrl
- applicationSpecificTag
- locationTag
- functionTag

Properties of are now mandatory! breaking change! 
- vendorName
- productName

Properties applicationSpecificTag, locationTag, functionTag have now a limitation of 32 characters!

deviceAlias has now a limitation of 32 characters!

deviceParametersGet
- parameterName limited to 71 characters
- new property subindexAccessSupported

deviceSubParametersGet
- subParameterName limited to 71 characters

**Comment by roeseko** [comment]
Discussion in WG meeting (08/05/2023):

- close this issue and open new ones if applicable
