### ISSUE TITLE
ipv4  has no pattern definition

### ISSUE THREAD

**Issue by mrentsch65** [iolinkcommunity/JSON_for_IO-Link#81]
like i.e. here for macAddress:

```
        macAddress:
          type: string
          pattern: '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$'
```
current specification is:
```
              ipAddress:
                type: string
                format: ipv4
```
where "ipv4" is not further defined. I propose to indroduce also a regex-pattern for semantic checking. Examples are here: https://www.oreilly.com/library/view/regular-expressions-cookbook/9780596802837/ch07s16.html

**Comment by mrentsch65** [comment]
A pattern definition for URLs could also be helpful:

        vendorUrl:
          type: string
          format: uri
          pattern: ^(?:(http?|s?ftp):\/\/|file:\/\/\/)?(([\P{Cc}]+):([\P{Cc}]+)@)?([a-zA-Z0-9][a-zA-Z0-9.-]*)(:[0-9]{1,5})?($|\/[\w\-\._~:\/?[\]@!\$&'\(\)\*\+,;=.]+(\#[\w]*)?$)

**Comment by roeseko** [comment]
ipv4 regex was introduced in PR #87
