### ISSUE TITLE
Proposal to remove GET/apiversion

### ISSUE THREAD

**Issue by mrentsch65** [iolinkcommunity/JSON_for_IO-Link#83]
The version information is already contained in the response of GET/openapi (the "version"-statement in the openapi file). Thus there is no need to have a separate endpoint for it.
![image](https://user-images.githubusercontent.com/50681355/225036937-5117a41b-a301-423f-b61c-fc2122b4c95e.png)

**Comment by roeseko** [comment]
I could see the use of this explicit endpoint to get the version directly and fast without reading and parsing a potential "big" open api document.
But of course the redundant version information could also result in discrepancy. 

Currently, I would leave it as it is but I am open for discussion.

**Comment by roeseko** [comment]
Decision in WG meeting (08/05/2023):
- reject issue and take the following discussion points to #90 
- make endpoint `/apiversion` mandatory
- make endpoint `/openapi` optional
- easy access to version
