### ISSUE TITLE
Example for master configuration is missing

### ISSUE THREAD

**Issue by roeseko** [iolinkcommunity/JSON_for_IO-Link#85]
`GET '/masters/{masterNumber}/configuration': `

**Comment by mrentsch65** [comment]
The idea is of having an assembly of configuration endpoints which can the client directly translate into single post requests, alternatively can the backend do it internally.

```
[
  {
    "/masters/1/ports/1/configuration": {
      "mode": "IOLINK_MANUAL",
      "validationAndBackup": "TYPE_COMPATIBLE_DEVICE_V1.1",
      "cycleTime": {
        "value": 2.3,
        "unit": "ms"
      },
      "vendorId": 26,
      "deviceId": 333,
      "iqConfiguration": "DIGITAL_INPUT",
      "deviceAlias": "Distance_sensor_1"
    }
  },
  {
    "/masters/1/ports/1/datastorage": {
      "header": {
        "vendorId": 26,
        "deviceId": 333,
        "ioLinkRevision": "1.1",
        "content": "TWFuIGlzIGRpc3Rpbmd1aXNoZWQsIG5vdCBvbmx5IGJ5IGhpcyByZWFzb24sIGJ1dCBieSB0aGl"
      }
    }
  },
  {
    "/masters/1/ports/2/configuration": {
      "mode": "IOLINK_AUTOSTART",
      "validationAndBackup": "TYPE_COMPATIBLE_DEVICE_V1.1",
      "cycleTime": {
        "value": 2.3,
        "unit": "ms",
        "vendorId": 15,
        "deviceId": 65253
      },
      "iqConfiguration": "DIGITAL_INPUT",
      "deviceAlias": "Flow_control_2"
    }
  },
  {
    "/devices/Flow_control_2/identification": {
      "applicationSpecificTag": "Flow control switch",
      "locationTag": "Down under",
      "functionTag": "Check start of belt"
    }
  },
  {
    "/devices/Flow_control_2/ports/2/blockparameterization": {
      "direction": "WRITE",
      "parameters": [
        {
          "identifier": {
            "parameterName": "Application_tag"
          },
          "content": {
            "value": "Level 2, row 3"
          }
        },
        {
          "identifier": {
            "parameterName": "Hysteresis",
            "subParameterName": "Channel_B"
          },
          "content": {
            "value": 123
          }
        }
      ]
    }
  }
]
```

**Comment by mrentsch65** [comment]
To be discussed: 
1) The same principle should also be applied to the wireless case. (@SebastianHag)
2) And it would be good to add in the GET-case a metadata-header with version information to such a configuration assembly. The metadata should contain information about the device (where the configuration came from) and the date/time it was generated.

**Comment by roeseko** [comment]
I agree that it might come in handy to have a assembly of configurations at on endpoint. But I think we should not blow up the master side to much. For example, how should the response look like if one of the configurations fails? What about timing and so on? 
In my opinion the client itself should be responsible for writing each config at a time and thereby keep it as simple as possible. This behavior is well defined and complaint with the standard http communication.

I would suggest to discuss this topic on our next meeting 24th of April.

**Comment by mrentsch65** [comment]
The goal I had in mind with my above example is targeting rather the definition of a standardized configuration file format based on JSON, which can be assembled in IO-Link-Engineering-Tools and applied from there to the IO-Link-Topology with the normal REST-API-POST-Commands.
I agree that we should stick with 'GET /masters/{masterNumber}/configuration' to master parameters and not adding device settings to it. I have thus reduced this in my pull request.

**Comment by roeseko** [comment]
Decision in WG meeting (08/05/2023):

- Issue will be rejected due to the following reasons:
  - possible lack of hardware resources of io-link gateways
  - error handling (e.g. parts of configuration fails)
  - complexity of configuration in regards of timing 
  - no new feature, could be solved by sequential enpoint access of clients 
  - if needed, it could be a vendor specific extension
