### ISSUE TITLE
New general endpoints should be kept outside URL versioning

### ISSUE THREAD

**Issue by mrentsch65** [iolinkcommunity/JSON_for_IO-Link#90]
This can be achieved as follows: 

![image](https://user-images.githubusercontent.com/50681355/232171579-8fbece1b-f876-41db-bdc9-9a3e2de7e1d9.png)

**Comment by roeseko** [comment]
Discussion in WG meeting (08/05/2023):
- General discussion regrading versioning -> what is the best way of versioning 
- Common understanding to release long term stable releases (~ once year)
- Consideration of user point of view on the interface 
- Changes in the specification need to be identified by version to be either extensions or incompatible adjustments
- 3 ways of versioning endpoints/specification:
  - Part of url (../v1/..)
  - Header information
  - Version can be read at /openapi or /apiversion

**Decision needs to be made how to continue version handling!**

**Comment by roeseko** [comment]
Decision in WG meeting (12/06/2023):
- keep major versioning in url path 
- minor versioning in GET/apiversion and yaml info:version:

**Comment by roeseko** [comment]
Decision in WG meeting (12/06/2023):
- keep major versioning in url path 
- minor versioning in GET/apiversion and yaml info:version:
