### ISSUE TITLE
Assignment of gateway configuration to pyhsical interface not clear 

### ISSUE THREAD

**Issue by roeseko** [iolinkcommunity/JSON_for_IO-Link#91]
Currently, the gateway configuration consists of an array of parameters like ip address, addressing mode etc. but it is not clear how it is assigned to the real physical interfaces.
![image](https://user-images.githubusercontent.com/95340986/233176153-42637f6e-cf75-419b-a3d1-303c7ce7e800.png)

**Comment by mrentsch65** [comment]
Proposal, should be backward compatible:
```
{
   "ethIpv4":[
      {
         "ifName":"eth0",
         "ipConfiguration":"MANUAL",
         "ipAddress":"192.168.1.13",
         "subnetMask":"255.255.255.0",
         "standardGateway":"192.168.1.1"
      },
      {
         "ifName":"eth1",
         "ipConfiguration":"DHCP",
         "ipAddress":"192.168.200.7",
         "subnetMask":"255.255.255.0",
         "standardGateway":"192.168.200.1"
      }
   ]
}
```

**Comment by julian-st** [comment]
Good idea! I would vote for interface as key name

**Comment by roeseko** [comment]
So, now we have two proposals:

1. `"ifName":"eth0"`

2. `"interface":"eth0"`

Please vote for the key name most suitable in your opinion!

**Comment by mrentsch65** [comment]
„ifName“ is a well established terminology for Network Interfaces and defined in RFC1573.Von meinem iPhone gesendetAm 24.04.2023 um 16:06 schrieb roeseko ***@***.***>:﻿
So, now we have two proposals:


"ifName":"eth0"


"interface":"eth0"


Please vote for the key name most suitable in your opinion!

**Comment by roeseko** [comment]
Hey guys 
Please have a look a the pull request and review.
