### ISSUE TITLE
IODD-Management cannot store and load device pictures

### ISSUE THREAD

**Issue by mrentsch65** [iolinkcommunity/JSON_for_IO-Link#95]
IODD-Management should be extended to store and load device pictures, i.e. via a new endpoint ```GET/iodds/image``` or  a query-parameter on ```GET/iodds/file?image```

**Comment by roeseko** [comment]
CR122 -> 11.04.22 Accepted : GET /iodds/file will be added by a query 
parameter to get also png files

**Comment by roesekoSICKAG** [comment]
Required changes are merged.
