### ISSUE TITLE
IODD-Management: " "ioLinkRevision" is probably misleading

### ISSUE THREAD

**Issue by mrentsch65** [iolinkcommunity/JSON_for_IO-Link#96]
Should this not be "profileRevision" or "ioddRevision" instead? 

The version nomenclature used in IODDs also indicates that ("V1.1" vs. "1.1"):

```
<ProfileRevision>1.1</ProfileRevision>

<CommNetworkProfile xsi:type="IOLinkCommNetworkProfileT" iolinkRevision="V1.1">
```

**Comment by OlafWestrik** [comment]
IODDIdentification

version: IODD/IODevice/DocumentInfo/@version,   see IODD specification
releaseDate: IODD/IODevice/DocumentInfo/@releaseDate,   see IODD specification

iolinkRevision: IODD/IODevice/ProfileHeader/ProfileRevision,   see IODD specification
or
iolinkRevision: <schema version> from IODD filename,   see IODD specification

**Comment by roesekoSICKAG** [comment]
Problem solved by changing the description and added a new enum value.
